###send message by no user
POST /sendMail HTTP/1.1
Host: localhost:8283

###send message by user
POST /sendMail HTTP/1.1
Host: localhost:8283
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IjEyNSIsImV4cCI6MTU5MjMyMjU2OX0.6TYb6pqXVgJ6EtQ17QwuUSEBGv5mlqgcX9qivE_fkBU

{
  "to": "persilolka@gmail.com",
  "mailHeader": "eee",
  "mailBody": "Hello, World!"
}

###send message without `to` by user
POST /sendMail HTTP/1.1
Host: localhost:8283
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IjEyNSIsImV4cCI6MTU5MjMyMjU2OX0.6TYb6pqXVgJ6EtQ17QwuUSEBGv5mlqgcX9qivE_fkBU

{
  "mailHeader": "Hello",
  "mailBody": "Hello, World!"
}

###