###send message by no user
POST /sendMail HTTP/1.1
Host: localhost:8283

###send message by user
POST /sendMail HTTP/1.1
Host: localhost:8283
Content-Type: application/json
Set-Cookie: token=

{
  "to": "persilolka@gmail.com",
  "mailHeader": "Hello",
  "mailBody": "Hello, World!"
}

###send message without `to` by user
POST /sendMail HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "mailHeader": "Hello",
  "mailBody": "Hello, World!"
}