GET / HTTP/1.1
Host: localhost:8283

###
###create user with empty params
###create user with params
POST /createUser HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "login": "125",
  "password": "122"
}
###delete user
###changePassword
###showUsers
