###create user with params
POST /createUser HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "login": "125",
  "password": "122"
}

###create user with empty params
POST /createUser HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "login": "",
  "password": ""
}

###authorize user with correct data
POST /authorize HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "login": "125",
  "password": "122"
}

###authorize user with incorrect data
POST /authorize HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "login": "125",
  "password": "33"
}

###delete user
GET /delete?login=nastya HTTP/1.1
Host: localhost:8283
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IjEyNSIsImV4cCI6MTU5MjMyNTkxNn0.QGLJHeTcFQm51yHN7WO5I-XSwm7tdJPHhHavav2mdPo

###changePassword
POST /changePassword HTTP/1.1
Host: localhost:8283
Content-Type: application/json

{
  "login": "125",
  "password": "122"
}


###showUsers
GET /showUsers HTTP/1.1
Host: localhost:8283

###